# Generated by Django 2.1.11 on 2019-09-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190828_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
